name: Update README

on:
  schedule:
    - cron: '* */12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test update to repo
      run: |
        echo "Test push commit to the remote in the workflow" >> test.txt

        git config --global user.name "Aditya Bisoi"
        git config --global user.email "adityabisoi1999@gmail.com"

        git add -A
        git commit -m "Update test.txt"
        git push